---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: standard  # Use the default standard storage class in GKE
  accessModes:
    - ReadWriteOnce  # Only one pod can mount this volume
  resources:
    requests:
      storage: 10Gi  # Request 10Gi of storage (adjust as necessary)

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  serviceName: "mongo"
  replicas: 1  # Number of replicas (can scale as needed)
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username  # Username stored in the secret
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: password  # Password stored in the secret
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db  # MongoDB's default data directory
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi  # Persistent volume size
        storageClassName: standard  # Use GKE's default storage class
